language: node_js
node_js:
- stable
cache:
  directories:
    - "node_modules"

notifications:
  slack:
    rooms:
      - vibn:fziwh78cHZvFWAZWJ7FYPzgY#desenvolvimento
    on_success: always

install:
  - npm install -g firebase-tools
  - npm install -g create-react-app
  - (cd client && npm install)
  - (cd functions && npm install)

script:
  - (cd client && npm run build)

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN