language: node_js
node_js:
- stable
cache:
  directories:
    - "node_modules"


install:
  - npm install -g firebase-tools
  - npm install -g create-react-app

script:
  - npm install
  - npm run test:CI
  - npm run build



after_success:
  - firebase deploy --token $FIREBASE_TOKEN